# Generated by Django 4.2.4 on 2023-12-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient/images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
