# Generated by Django 4.2.4 on 2023-12-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctor_designation_alter_doctor_specialization_and_more'),
        ('appoinments', '0002_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.avialabletimefordoctor'),
        ),
    ]
