# Generated by Django 4.2.4 on 2023-12-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_rename_scheduletime_availabltime_and_more'),
        ('appoinments', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.ManyToManyField(to='doctor.availabltime'),
        ),
    ]
