# Generated by Django 4.2.4 on 2023-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0006_appointment_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
