# Generated by Django 4.2.4 on 2023-12-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_time',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='doctor',
            field=models.ManyToManyField(to='doctor.doctor'),
        ),
    ]
