# Generated by Django 4.2.4 on 2023-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_delete_availabletime_avialabletimefordoctor_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
