# Generated by Django 4.2.4 on 2023-12-20 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0006_doctor_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.ManyToManyField(related_name='designations', to='doctor.designation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(related_name='specializations', to='doctor.specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
