# Generated by Django 4.2.4 on 2023-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctor_designation_alter_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.ManyToManyField(to='doctor.scheduletime'),
        ),
    ]
