# Generated by Django 4.2.4 on 2023-12-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_time',
        ),
    ]
