# Generated by Django 4.2.4 on 2023-12-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0003_alter_appointment_time'),
        ('doctor', '0009_remove_doctor_available_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleTime',
            new_name='AvailablTime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.ManyToManyField(to='doctor.availabltime'),
        ),
        migrations.DeleteModel(
            name='AvialableTimeForDoctor',
        ),
    ]
