# Generated by Django 4.2.4 on 2023-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_rename_scheduletime_availabltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
