# Generated by Django 4.2.4 on 2023-12-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0005_rename_symtom_appointment_symptom_and_more'),
        ('doctor', '0011_designation_slug_specialization_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailablTime',
            new_name='AvailableTime',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
